### ISSUE TITLE
Unable to import and use the package

### ISSUE THREAD

**Issue by shivamahuja99** [bedapudi6788/deeppunct#20]
`from deepcorrect import DeepCorrect
corrector = DeepCorrect('params_path', 'checkpoint_path')
corrector.correct('how are you')`

**im getting error like**
`Traceback (most recent call last):

  File "C:\Users\skullcandy\AppData\Roaming\Python\Python38\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-af9bfbc070b3>", line 1, in <module>
    from deepcorrect import DeepCorrect

  File "C:\Users\skullcandy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\deepcorrect\__init__.py", line 1, in <module>
    from .deepcorrect import DeepCorrect

  File "C:\Users\skullcandy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\deepcorrect\deepcorrect.py", line 1, in <module>
    from txt2txt import build_model, infer

  File "C:\Users\skullcandy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\txt2txt\__init__.py", line 3, in <module>
    from .txt2txt import *

  File "C:\Users\skullcandy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\txt2txt\txt2txt.py", line 7, in <module>
    import tensorflow as tf

  File "C:\Users\skullcandy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\Users\skullcandy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\skullcandy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *

  File "C:\Users\skullcandy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 114
    def TFE_ContextOptionsSetAsync(arg1, async):
                                         ^
SyntaxError: invalid syntax
`

**Can you help me in using it**

**Comment by bedapudi6788** [comment]
Check if you are able to import tensorflow without issues.

**Comment by shivamahuja99** [comment]
no im not able to use it , can you help me in that?

**Comment by bedapudi6788** [comment]
No, sorry.
